name: atproto_test
description: This package provides core reusable and useful functionality for testing atproto based packages.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.3.0

dependencies:
  test: ^1.21.0
  atproto_core: ^1.0.0-preview.0
  http: ^1.2.1
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.0.1
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
