name: atproto_test
description: This package provides core reusable and useful functionality for testing atproto based packages.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.8.0

dependencies:
  test: ^1.26.2
  atproto_core: ^0.11.0
  http: ^1.4.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^6.0.0
  import_sorter: ^4.6.0
