name: bluesky_text
description: Provides the easiest and most powerful way to analyze the text on Bluesky Social.
version: 0.5.3
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky_text
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - util

dependencies:
  xrpc: ^0.3.2
  characters: ^1.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  icann_tlds: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  import_sorter: ^4.6.0
  bluesky: ^0.8.5

import_sorter:
  emojis: true
