name: bluesky_text
description: Provides the easiest and most powerful way to analyze the text on Bluesky Social.
version: 0.0.1
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky_text
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  characters: ^1.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
