name: lex_annotation
description: >
  Annotations for the lex_gen.
  This package does nothing without lex_gen.
version: 0.0.2
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/lex_annotation
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.8.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - annotation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  import_sorter: ^4.6.0
