name: lexicon
description: Core library for parsing Lexicon in the AT Protocol standard.
version: 0.2.5
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/packages/lexicon
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.3.0

dependencies:
  nsid: ^0.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.25.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  import_sorter: ^4.6.0
