name: lexicon
description: AT Protocol standard Lexicon objects for Dart and Flutter
version: 0.0.0
repository: https://github.com/myConsciousness/atproto.dart/packages/lexicon
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_schema2: ^2.0.4+3
  nsid: ^0.0.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
