name: xrpc
description: Provide an HTTP client specialized for XRPC communication in AT Protocol.
version: 0.4.2
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/intro
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/xrpc
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - http
  - xrpc

dependencies:
  http: ^1.1.0
  nsid: ^0.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mime: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  import_sorter: ^4.6.0

import_sorter:
  emojis: true

screenshots:
  - description: The xrpc package and atproto.dart logo.
    path: screenshots/logo.png
