name: xrpc_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  atproto: ^0.3.0
  http: ^0.13.6
  xrpc: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
