name: atproto_core
description: This package provides core reusable and useful functionality for wrapping AT Protocol and related services.
version: 0.6.2
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/intro
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto_core
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - api
  - core

dependencies:
  xrpc: ^0.4.2
  at_uri: ^0.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cbor: ^6.1.1
  multiformats: ^0.2.1
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test

import_sorter:
  emojis: true

screenshots:
  - description: The atproto_core package and atproto.dart logo.
    path: screenshots/logo.png
