name: atproto_core
resolution: workspace
description: Core library for clients and tools. This package is mainly used by https://atprotodart.com packages.
version: 1.1.0
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/intro
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto_core
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.8.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - api
  - core

dependencies:
  xrpc: ^1.0.3
  at_primitives: ^1.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cbor: ^6.3.7
  multiformats: ^1.0.2
  atproto_oauth: ^0.1.2
  nanoid: ^1.0.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.2.0
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces

  atproto_test:
    path: ../atproto_test
