name: atproto
description: The easiest and powerful Dart/Flutter library for AT Protocol.
version: 0.2.12
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  atproto_core: ^0.2.9
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  atproto_test: ^0.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
