name: atproto
description: The most famous and powerful Dart/Flutter library for AT Protocol.
version: 0.13.3
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/packages/atproto
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.3.0

topics:
  - atproto
  - bluesky
  - api

dependencies:
  atproto_core: ^0.11.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.25.2
  build_runner: ^2.4.8
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test
