name: atproto
resolution: workspace
description: The most famous and powerful Dart/Flutter library for AT Protocol.
version: 1.3.0
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/packages/atproto
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.8.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - api

dependencies:
  atproto_core: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.2.0
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces

  atproto_test:
    path: ../atproto_test
