name: atproto
description: The most famous and powerful Dart/Flutter library for AT Protocol.
version: 0.8.3
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/packages/atproto
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - api

dependencies:
  atproto_core: ^0.6.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test

import_sorter:
  emojis: true

screenshots:
  - description: The atproto package and atproto.dart logo.
    path: screenshots/logo.png
