name: atproto
description: The easiest and powerful Dart/Flutter library for AT Protocol.
version: 0.5.6
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=2.17.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - api

dependencies:
  atproto_core: ^0.4.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test

import_sorter:
  emojis: true
