name: bluesky_cards
description: Provide widgets to render Bluesky Social post beautifully in Flutter app.
version: 0.0.9
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky_cards
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

topics:
  - atproto
  - bluesky
  - widget

dependencies:
  flutter:
    sdk: flutter
  bluesky: ^0.7.6
  cached_network_image: ^3.2.3
  html_unescape: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/bsky___ic_brand.png
    - assets/bsky___ic_reposted_by.png
    - assets/bsky___ic_verified_badge.png

  fonts:
    - family: Roboto

      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
