name: bluesky_cli
resolution: workspace
description: A powerful CLI tool that allows Bluesky Social's APIs to be executed from the command line powered by Dart language.
version: 0.4.7
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky_cli
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.8.0 <4.0.0"

executables:
  bsky:

topics:
  - atproto
  - bluesky
  - api
  - cli

dependencies:
  xrpc: ^1.0.3
  at_primitives: ^1.0.0
  ansi_styles: ^0.3.1
  args: ^2.7.0
  cli_launcher: ^0.3.1
  cli_util: ^0.4.2
  bluesky_text: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces
