name: bluesky_cli
description: A powerful CLI tool that allows Bluesky Social's APIs to be executed from the command line powered by Dart language.
version: 0.3.8
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky_cli
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

executables:
  bsky:

topics:
  - atproto
  - bluesky
  - api
  - cli

dependencies:
  xrpc: ^0.3.2
  at_uri: ^0.2.2
  ansi_styles: ^0.3.1
  args: ^2.0.0
  cli_launcher: ^0.3.0
  cli_util: ^0.3.0
  bluesky_text: ^0.5.10

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
