name: multiformats
description: Provide useful interfaces such a CID used by AT Protocol to Dart/Flutter.
version: 0.2.0
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/multiformats
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - ipfs
  - atproto
  - bluesky
  - cid

dependencies:
  base_codecs: ^1.0.1
  crypto: ^3.0.3
  dart_multihash: ^1.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
