name: bluesky_post
description: A server app using the shelf package and Docker.
version: 5.0.0
publish_to: none
environment:
  sdk: ^3.0.0

dependencies:
  actions_toolkit_dart: ^0.5.1
  bluesky: ^0.10.4
  bluesky_text: ^0.6.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
