name: did_plc
description: Support for DID PLC Directory endpoints used by atproto and other services.
version: 0.0.5
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/did_plc
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - plc

dependencies:
  atproto_core: ^0.7.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  import_sorter: ^4.6.0
  atproto_test:
    path: ../atproto_test

import_sorter:
  emojis: true