name: lex_gen
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
 lexicon: ^1.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces
