name: at_uri
description: Provide standard uri supported by AT Protocol to Dart/Flutter.
version: 0.2.2
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/at_uri
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - uri
  - util

dependencies:
  at_identifier: ^0.2.0
  nsid: ^0.2.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true

screenshots:
  - description: The at_uri package and atproto.dart logo.
    path: screenshots/logo.png
