name: bluesky
description: The most famous and powerful Dart/Flutter library for Bluesky Social.
version: 1.0.0-preview.0
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/packages/bluesky
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.3.0

topics:
  - atproto
  - bluesky
  - api

dependencies:
  atproto_core: ^1.0.0-preview.0
  atproto: ^1.0.0-0.0.dev
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  characters: ^1.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  import_sorter: ^4.6.0
  bluesky_text: ^0.6.9

  atproto_test:
    path: ../atproto_test

import_sorter:
  emojis: true

screenshots:
  - description: The bluesky package and atproto.dart logo.
    path: screenshots/logo.png
