name: atproto_oauth
description: Provides tools to handle OAuth for AT Protocol and Bluesky Social.
version: 0.0.1
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto_oauth
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.3.0

topics:
  - atproto
  - bluesky
  - oauth

dependencies:
  http: ^1.2.1
  crypto: ^3.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pointycastle: ^3.9.1
  convert: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
