name: Auto Mirror Lexicons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Delete Old Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/auto-mirror-lexicons; then
            git push origin --delete auto-mirror-lexicons
          fi

      - name: Create New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c auto-mirror-lexicons
          git push -u origin auto-mirror-lexicons

      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get

      - name: Auto Mirror Lexicons
        run: dart run ./bin/mirror_lexicons.dart
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Generate Lexicon IDs
        run: dart run ./bin/generate_lexicon_ids.dart

      - name: Format All
        run: melos format

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[Scheduled] Auto Mirror Lexicons"
          title: "[Scheduled] Auto Mirror Lexicons"
          branch: auto-mirror-lexicons
          base: main
          labels: Github Actions
          assignees: "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
