name: Generate Codes

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  generate-codes:
    if: github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'chore-sync-lexicons'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Delete Old Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/chore-generate-codes; then
            git push origin --delete chore-generate-codes
          fi

      - name: Create New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c chore-generate-codes
          git push -u origin chore-generate-codes

      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: |
          dart pub get
          cd packages/atproto
          dart pub get
          cd ../../packages/bluesky
          dart pub get
          cd ../../packages/bluesky_cli
          dart pub get
          cd ../../

      - name: Generate
        run: |
          dart run ./scripts/gen_lexicon_docs.dart
          dart run ./scripts/gen_lexicon_ids.dart
          dart run ./scripts/gen_lexicon_matrix.dart
          dart run ./scripts/gen_supported_api_matrix.dart
          dart run ./scripts/gen_codes.dart

      - name: Build
        run: |
          cd packages/atproto
          dart run build_runner build --delete-conflicting-outputs
          cd ../../packages/bluesky
          dart run build_runner build --delete-conflicting-outputs
          cd ../../

      - name: Format
        run: |
          cd packages/lexicon
          dart fix --apply
          dart run import_sorter:main
          dart format .
          cd ../../packages/atproto
          dart fix --apply
          dart run import_sorter:main
          dart format .
          cd ../../packages/bluesky
          dart fix --apply
          dart run import_sorter:main
          dart format .
          cd ../../packages/bluesky_cli
          dart fix --apply
          dart run import_sorter:main
          dart format .
          cd ../../

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: Update source files automatically"
          title: "chore: Update source files automatically"
          branch: chore-generate-codes
          base: main
          labels: Github Actions
          assignees: "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
